"""
add query and correct request.

Revision ID: 6f40545b8e99
Revises: f331fe4b527d
Create Date: 2024-11-03 20:30:39.764941

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6f40545b8e99'
down_revision: str | None = 'f331fe4b527d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Up migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'queries',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('sql', sa.String(), nullable=False),
        sa.Column('params', sa.JSON(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('duration', sa.Float(), nullable=False),
        sa.Column('traceback', sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_queries_id'), 'queries', ['id'], unique=False)
    op.add_column('requests', sa.Column('timestamp', sa.DateTime(), nullable=False))
    op.drop_column('requests', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Down migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('username', sa.DATETIME(), nullable=False))
    op.drop_column('requests', 'timestamp')
    op.drop_index(op.f('ix_queries_id'), table_name='queries')
    op.drop_table('queries')
    # ### end Alembic commands ###
